on: [push]

name: AWS ElastikBeanstalk Deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@master

    - name: Generate deployment package
      run: zip deploy${{ github.sha }}.zip *

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v10
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: dashboard
        environment_name: Dashboard-env
        version_label: ${{ github.sha }}
        region: us-east-2
        deployment_package: deploy${{ github.sha }}.zip