on: [push]

name: azure app service deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Login to DockerHub Registry'
      uses: azure/docker-login@v1
      with:
          login-server: index.docker.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        echo 'building image and pushing it to docker hub'
        echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
        docker build . -t houssemtebai/dashboard:${{ github.sha }}
        docker push houssemtebai/dashboard:${{ github.sha }}
    
    - uses: azure/webapps-container-deploy@v1
      with:
        app-name: 'myDashbord'
        images: 'houssemtebai/dashboard:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout
